DotNetMvcCMS/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetMvcCMS.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/
        public ActionResult Index()
        {
            return View();
        }
	}
}

DotNetMvcCMS/Controllers/AdminLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetMvcCMS.Controllers
{
    public class AdminLayoutController : Controller
    {
        //
        // GET: /AdminLayout/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TopBar()
        {
            return View();
        }

        public ActionResult BreadScrumbs()
        {
            return View();
        }

        public ActionResult Menu()
        {
            return View();
        }

        public ActionResult MainContent()
        {
            return View();
        }

        public ActionResult Setting()
        {
            return View();
        }
	}
}

DotNetMvcCMS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetMvcCMS.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
            return View();
        }
	}
}

DotNetMvcCMS/Controllers/HomeLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetMvcCMS.Controllers
{
    public class HomeLayoutController : Controller
    {
        //
        // GET: /HomeLayout/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Header()
        {
            return View();
        }

        public ActionResult Slider()
        {
            return View();
        }
        #region LeftSide
        public ActionResult LeftSideCategory()
        {
            return View();
        }

        public ActionResult LeftSideBrand()
        {
            return View();
        }

        public ActionResult LeftSidePrice()
        {
            return View();
        }

        public ActionResult LeftSideImage()
        {
            return View();
        }
#endregion

        #region RightContent
        public ActionResult RightBoxItems()
        {
            return View();
        }

        public ActionResult RightBoxItemsWithSlider()
        {
            return View();
        }
        #endregion

        public ActionResult ItemDetail()
        {
            return View();
        }

        public ActionResult RightBoxItemsWithCategoryTab()
        {
            return View();
        }

        public ActionResult Footer()
        {
            return View();
        }
	}
}

DotNetMvcCMS/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetMvcCMS.Controllers
{
    public class ItemController : Controller
    {
        //
        // GET: /Item/
        public ActionResult Index()
        {
            return View();
        }
	}
}

DotNetMvcCMS/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Admin/Layout.cshtml";
}
<div class="navbar">
    <div class="navbar-inner">
        <div class="container-fluid">
            @{Html.RenderAction("TopBar", "AdminLayout");}
        </div><!--/.container-fluid-->
    </div><!--/.navbar-inner-->
</div>

<div class="main-container container-fluid">
    <a class="menu-toggler" id="menu-toggler" href="#">
        <span class="menu-text"></span>
    </a>

    <div class="sidebar" id="sidebar">
        @{Html.RenderAction("Menu", "AdminLayout");}
    </div>

    <div class="main-content">
        
        @{Html.RenderAction("BreadScrumbs", "AdminLayout");}
        <div class="page-content">
          @{Html.RenderAction("MainContent","AdminLayout");}
        </div><!--/.page-content-->

        @{Html.RenderAction("Setting", "AdminLayout");}
 </div><!--/.main-content-->
</div>

DotNetMvcCMS/Views/AdminLayout/BreadScrumbs.cshtml
<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="#">Home</a>

            <span class="divider">
                <i class="icon-angle-right arrow-icon"></i>
            </span>
        </li>
        <li class="active">Dashboard</li>
    </ul><!--.breadcrumb-->

    <div class="nav-search" id="nav-search">
        <form class="form-search" />
        <span class="input-icon">
            <input type="text" placeholder="Search ..." class="input-small nav-search-input" id="nav-search-input" autocomplete="off" />
            <i class="icon-search nav-search-icon"></i>
        </span>
        </form>
    </div><!--#nav-search-->
</div>

DotNetMvcCMS/Views/AdminLayout/Menu.cshtml
<div class="sidebar-shortcuts" id="sidebar-shortcuts">
    <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
        <button class="btn btn-small btn-success">
            <i class="icon-signal"></i>
        </button>

        <button class="btn btn-small btn-info">
            <i class="icon-pencil"></i>
        </button>

        <button class="btn btn-small btn-warning">
            <i class="icon-group"></i>
        </button>

        <button class="btn btn-small btn-danger">
            <i class="icon-cogs"></i>
        </button>
    </div>

    <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
        <span class="btn btn-success"></span>

        <span class="btn btn-info"></span>

        <span class="btn btn-warning"></span>

        <span class="btn btn-danger"></span>
    </div>
</div><!--#sidebar-shortcuts-->

<ul class="nav nav-list">
    <li class="active">
        <a href="index.html">
            <i class="icon-dashboard"></i>
            <span class="menu-text"> Dashboard </span>
        </a>
    </li>

    <li>
        <a href="typography.html">
            <i class="icon-text-width"></i>
            <span class="menu-text"> Typography </span>
        </a>
    </li>

    <li>
        <a href="#" class="dropdown-toggle">
            <i class="icon-desktop"></i>
            <span class="menu-text"> UI Elements </span>

            <b class="arrow icon-angle-down"></b>
        </a>

        <ul class="submenu">
            <li>
                <a href="elements.html">
                    <i class="icon-double-angle-right"></i>
                    Elements
                </a>
            </li>

            <li>
                <a href="buttons.html">
                    <i class="icon-double-angle-right"></i>
                    Buttons &amp; Icons
                </a>
            </li>

            <li>
                <a href="treeview.html">
                    <i class="icon-double-angle-right"></i>
                    Treeview
                </a>
            </li>

            <li>
                <a href="#" class="dropdown-toggle">
                    <i class="icon-double-angle-right"></i>

                    Three Level Menu
                    <b class="arrow icon-angle-down"></b>
                </a>

                <ul class="submenu">
                    <li>
                        <a href="#">
                            <i class="icon-leaf"></i>
                            Item #1
                        </a>
                    </li>

                    <li>
                        <a href="#" class="dropdown-toggle">
                            <i class="icon-pencil"></i>

                            4th level
                            <b class="arrow icon-angle-down"></b>
                        </a>

                        <ul class="submenu">
                            <li>
                                <a href="#">
                                    <i class="icon-plus"></i>
                                    Add Product
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <i class="icon-eye-open"></i>
                                    View Products
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>

    <li>
        <a href="tables.html">
            <i class="icon-list"></i>
            <span class="menu-text"> Tables </span>
        </a>
    </li>

    <li>
        <a href="#" class="dropdown-toggle">
            <i class="icon-edit"></i>
            <span class="menu-text"> Forms </span>

            <b class="arrow icon-angle-down"></b>
        </a>

        <ul class="submenu">
            <li>
                <a href="form-elements.html">
                    <i class="icon-double-angle-right"></i>
                    Form Elements
                </a>
            </li>

            <li>
                <a href="form-wizard.html">
                    <i class="icon-double-angle-right"></i>
                    Wizard &amp; Validation
                </a>
            </li>

            <li>
                <a href="wysiwyg.html">
                    <i class="icon-double-angle-right"></i>
                    Wysiwyg &amp; Markdown
                </a>
            </li>
        </ul>
    </li>

    <li>
        <a href="widgets.html">
            <i class="icon-list-alt"></i>
            <span class="menu-text"> Widgets </span>
        </a>
    </li>

    <li>
        <a href="calendar.html">
            <i class="icon-calendar"></i>

            <span class="menu-text">
                Calendar
                <span class="badge badge-transparent tooltip-error" title="2&nbsp;Important&nbsp;Events">
                    <i class="icon-warning-sign red bigger-130"></i>
                </span>
            </span>
        </a>
    </li>

    <li>
        <a href="gallery.html">
            <i class="icon-picture"></i>
            <span class="menu-text"> Gallery </span>
        </a>
    </li>

    <li>
        <a href="#" class="dropdown-toggle">
            <i class="icon-tag"></i>
            <span class="menu-text"> More Pages </span>

            <b class="arrow icon-angle-down"></b>
        </a>

        <ul class="submenu">
            <li>
                <a href="profile.html">
                    <i class="icon-double-angle-right"></i>
                    User Profile
                </a>
            </li>

            <li>
                <a href="pricing.html">
                    <i class="icon-double-angle-right"></i>
                    Pricing Tables
                </a>
            </li>

            <li>
                <a href="invoice.html">
                    <i class="icon-double-angle-right"></i>
                    Invoice
                </a>
            </li>

            <li>
                <a href="login.html">
                    <i class="icon-double-angle-right"></i>
                    Login &amp; Register
                </a>
            </li>
        </ul>
    </li>

    <li>
        <a href="#" class="dropdown-toggle">
            <i class="icon-file-alt"></i>

            <span class="menu-text">
                Other Pages
                <span class="badge badge-primary ">4</span>
            </span>

            <b class="arrow icon-angle-down"></b>
        </a>

        <ul class="submenu">
            <li>
                <a href="error-404.html">
                    <i class="icon-double-angle-right"></i>
                    Error 404
                </a>
            </li>

            <li>
                <a href="error-500.html">
                    <i class="icon-double-angle-right"></i>
                    Error 500
                </a>
            </li>

            <li>
                <a href="grid.html">
                    <i class="icon-double-angle-right"></i>
                    Grid
                </a>
            </li>

            <li>
                <a href="blank.html">
                    <i class="icon-double-angle-right"></i>
                    Blank Page
                </a>
            </li>
        </ul>
    </li>
</ul><!--/.nav-list-->

<div class="sidebar-collapse" id="sidebar-collapse">
    <i class="icon-double-angle-left"></i>
</div>

DotNetMvcCMS/Views/AdminLayout/Setting.cshtml
<div class="ace-settings-container" id="ace-settings-container">
    <div class="btn btn-app btn-mini btn-warning ace-settings-btn" id="ace-settings-btn">
        <i class="icon-cog bigger-150"></i>
    </div>

    <div class="ace-settings-box" id="ace-settings-box">
        <div>
            <div class="pull-left">
                <select id="skin-colorpicker" class="hide">
                    <option data-class="default" value="#438EB9" />#438EB9
                    <option data-class="skin-1" value="#222A2D" />#222A2D
                    <option data-class="skin-2" value="#C6487E" />#C6487E
                    <option data-class="skin-3" value="#D0D0D0" />#D0D0D0
                </select>
            </div>
            <span>&nbsp; Choose Skin</span>
        </div>

        <div>
            <input type="checkbox" class="ace-checkbox-2" id="ace-settings-header" />
            <label class="lbl" for="ace-settings-header"> Fixed Header</label>
        </div>

        <div>
            <input type="checkbox" class="ace-checkbox-2" id="ace-settings-sidebar" />
            <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
        </div>

        <div>
            <input type="checkbox" class="ace-checkbox-2" id="ace-settings-breadcrumbs" />
            <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
        </div>

        <div>
            <input type="checkbox" class="ace-checkbox-2" id="ace-settings-rtl" />
            <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
        </div>
    </div>
</div><!--/#ace-settings-container-->

DotNetMvcCMS/Views/AdminLayout/TopBar.cshtml
<a href="#" class="brand">
    <small>
        <i class="icon-leaf"></i>
        Ace Admin
    </small>
</a><!--/.brand-->

<ul class="nav ace-nav pull-right">
    <li class="grey">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-tasks"></i>
            <span class="badge badge-grey">4</span>
        </a>

        <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-closer">
            <li class="nav-header">
                <i class="icon-ok"></i>
                4 Tasks to complete
            </li>

            <li>
                <a href="#">
                    <div class="clearfix">
                        <span class="pull-left">Software Update</span>
                        <span class="pull-right">65%</span>
                    </div>

                    <div class="progress progress-mini ">
                        <div style="width:65%" class="bar"></div>
                    </div>
                </a>
            </li>

            <li>
                <a href="#">
                    <div class="clearfix">
                        <span class="pull-left">Hardware Upgrade</span>
                        <span class="pull-right">35%</span>
                    </div>

                    <div class="progress progress-mini progress-danger">
                        <div style="width:35%" class="bar"></div>
                    </div>
                </a>
            </li>

            <li>
                <a href="#">
                    <div class="clearfix">
                        <span class="pull-left">Unit Testing</span>
                        <span class="pull-right">15%</span>
                    </div>

                    <div class="progress progress-mini progress-warning">
                        <div style="width:15%" class="bar"></div>
                    </div>
                </a>
            </li>

            <li>
                <a href="#">
                    <div class="clearfix">
                        <span class="pull-left">Bug Fixes</span>
                        <span class="pull-right">90%</span>
                    </div>

                    <div class="progress progress-mini progress-success progress-striped active">
                        <div style="width:90%" class="bar"></div>
                    </div>
                </a>
            </li>

            <li>
                <a href="#">
                    See tasks with details
                    <i class="icon-arrow-right"></i>
                </a>
            </li>
        </ul>
    </li>

    <li class="purple">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-bell-alt icon-animated-bell"></i>
            <span class="badge badge-important">8</span>
        </a>

        <ul class="pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-closer">
            <li class="nav-header">
                <i class="icon-warning-sign"></i>
                8 Notifications
            </li>

            <li>
                <a href="#">
                    <div class="clearfix">
                        <span class="pull-left">
                            <i class="btn btn-mini no-hover btn-pink icon-comment"></i>
                            New Comments
                        </span>
                        <span class="pull-right badge badge-info">+12</span>
                    </div>
                </a>
            </li>

            <li>
                <a href="#">
                    <i class="btn btn-mini btn-primary icon-user"></i>
                    Bob just signed up as an editor ...
                </a>
            </li>

            <li>
                <a href="#">
                    <div class="clearfix">
                        <span class="pull-left">
                            <i class="btn btn-mini no-hover btn-success icon-shopping-cart"></i>
                            New Orders
                        </span>
                        <span class="pull-right badge badge-success">+8</span>
                    </div>
                </a>
            </li>

            <li>
                <a href="#">
                    <div class="clearfix">
                        <span class="pull-left">
                            <i class="btn btn-mini no-hover btn-info icon-twitter"></i>
                            Followers
                        </span>
                        <span class="pull-right badge badge-info">+11</span>
                    </div>
                </a>
            </li>

            <li>
                <a href="#">
                    See all notifications
                    <i class="icon-arrow-right"></i>
                </a>
            </li>
        </ul>
    </li>

    <li class="green">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-envelope icon-animated-vertical"></i>
            <span class="badge badge-success">5</span>
        </a>

        <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-closer">
            <li class="nav-header">
                <i class="icon-envelope-alt"></i>
                5 Messages
            </li>

            <li>
                <a href="#">
                    <img src="~/Content/Admin/avatars/avatar.png" class="msg-photo" alt="Alex's Avatar" />
                    <span class="msg-body">
                        <span class="msg-title">
                            <span class="blue">Alex:</span>
                            Ciao sociis natoque penatibus et auctor ...
                        </span>

                        <span class="msg-time">
                            <i class="icon-time"></i>
                            <span>a moment ago</span>
                        </span>
                    </span>
                </a>
            </li>

            <li>
                <a href="#">
                    <img src="~/Content/Admin/avatars/avatar3.png" class="msg-photo" alt="Susan's Avatar" />
                    <span class="msg-body">
                        <span class="msg-title">
                            <span class="blue">Susan:</span>
                            Vestibulum id ligula porta felis euismod ...
                        </span>

                        <span class="msg-time">
                            <i class="icon-time"></i>
                            <span>20 minutes ago</span>
                        </span>
                    </span>
                </a>
            </li>

            <li>
                <a href="#">
                    <img src="~/Content/Admin/avatars/avatar4.png" class="msg-photo" alt="Bob's Avatar" />
                    <span class="msg-body">
                        <span class="msg-title">
                            <span class="blue">Bob:</span>
                            Nullam quis risus eget urna mollis ornare ...
                        </span>

                        <span class="msg-time">
                            <i class="icon-time"></i>
                            <span>3:15 pm</span>
                        </span>
                    </span>
                </a>
            </li>

            <li>
                <a href="#">
                    See all messages
                    <i class="icon-arrow-right"></i>
                </a>
            </li>
        </ul>
    </li>

    <li class="light-blue">
        <a data-toggle="dropdown" href="#" class="dropdown-toggle">
            <img class="nav-user-photo" src="~/Content/Admin/avatars/user.jpg" alt="Jason's Photo" />
            <span class="user-info">
                <small>Welcome,</small>
                Jason
            </span>

            <i class="icon-caret-down"></i>
        </a>

        <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer">
            <li>
                <a href="#">
                    <i class="icon-cog"></i>
                    Settings
                </a>
            </li>

            <li>
                <a href="#">
                    <i class="icon-user"></i>
                    Profile
                </a>
            </li>

            <li class="divider"></li>

            <li>
                <a href="#">
                    <i class="icon-off"></i>
                    Logout
                </a>
            </li>
        </ul>
    </li>
</ul><!--/.ace-nav-->

DotNetMvcCMS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Home/Layout.cshtml";
}

@{Html.RenderAction("Slider", "HomeLayout");}
<section>
    <div class="container">
        <div class="row">
            <!--Start Left Side-->
            <div class="col-sm-3">
                <div class="left-sidebar">
                    @{Html.RenderAction("LeftSideCategory", "HomeLayout");}
                    @{Html.RenderAction("LeftSideBrand", "HomeLayout");}
                    @{Html.RenderAction("LeftSidePrice", "HomeLayout");}
                    @{Html.RenderAction("LeftSideImage", "HomeLayout");}
                </div>
            </div>
            <!--End Left Side-->
            <div class="col-sm-9 padding-right">
                @{Html.RenderAction("ItemDetail", "HomeLayout");}
                @{Html.RenderAction("RightBoxItems", "HomeLayout");}
                @{Html.RenderAction("RightBoxItemsWithSlider", "HomeLayout");}
                @{Html.RenderAction("RightBoxItemsWithCategoryTab", "HomeLayout");}
            </div>
               
            </div>
    </div>
</section>

DotNetMvcCMS/Views/HomeLayout/Header.cshtml
<header id="header">
    <!--header-->
    <div class="header_top">
        <!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a href="index.html"><img src="images/home/logo.png" alt="" /></a>
                    </div>
                    <div class="btn-group pull-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                USA
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canada</a></li>
                                <li><a href="#">UK</a></li>
                            </ul>
                        </div>

                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                DOLLAR
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canadian Dollar</a></li>
                                <li><a href="#">Pound</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-user"></i> Account</a></li>
                            <li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
                            <li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
                            <li><a href="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>
                            <li><a href="login.html"><i class="fa fa-lock"></i> Login</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a href="index.html" class="active">Home</a></li>
                            <li class="dropdown">
                                <a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="shop.html">Products</a></li>
                                    <li><a href="product-details.html">Product Details</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="login.html">Login</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="blog.html">Blog List</a></li>
                                    <li><a href="blog-single.html">Blog Single</a></li>
                                </ul>
                            </li>
                            <li><a href="404.html">404</a></li>
                            <li><a href="contact-us.html">Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search" />
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

DotNetMvcCMS/Views/HomeLayout/LeftSideImage.cshtml
        <div class="shipping text-center">
            <!--shipping-->
            <img src="images/home/shipping.jpg" alt="" />
        </div><!--/shipping-->

DotNetMvcCMS/Views/HomeLayout/RightContent.cshtml
<div class="col-sm-9 padding-right">
    @{Html.RenderAction("FeaturedItemsBox", "HomeLayout");}
    @{Html.RenderAction("CategoryTab", "HomeLayout");}
    @{Html.RenderAction("RecommendedItemsBox", "HomeLayout");}
</div>

DotNetMvcCMS/Views/Shared/Home/Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Home/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Home/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Home/css/prettyPhoto.css" rel="stylesheet" />
    <link href="~/Content/Home/css/price-range.css" rel="stylesheet" />
    <link href="~/Content/Home/css/animate.css" rel="stylesheet" />
    <link href="~/Content/Home/css/main.css" rel="stylesheet" />
    <link href="~/Content/Home/css/responsive.css" rel="stylesheet" />
</head>
<body>
    <div>
        @{Html.RenderAction("Header", "HomeLayout");}
        @RenderBody()
        @{Html.RenderAction("Footer", "HomeLayout");}
    </div>
    <script src="~/Content/Home/js/jquery.js"></script>
    <script src="~/Content/Home/js/bootstrap.min.js"></script>
    <script src="~/Content/Home/js/jquery.scrollUp.min.js"></script>
    <script src="~/Content/Home/js/price-range.js"></script>
    <script src="~/Content/Home/js/jquery.prettyPhoto.js"></script>
    <script src="~/Content/Home/js/main.js"></script>
</body>
</html>